services: 

  fastapi:
    image: fastapi
    build: ./fastapi
    volumes:
      - ./fastapi:/app
    ports:
      - 8080:8080
    environment:
      - PORT=8080

  streamlit:
    image: streamlit
    build: ./streamlit
    volumes:
      - ./streamlit:/app
    ports:
      - 8501:8501
    environment:
      - PORT=8501      